## Default values for Traefik
image:
  name: traefik
  tag: 2.0.5
#
deployment:
  replicas: 1
#
ports:
  web:
    port: 8000
  websecure:
    port: 8443
  traefik:
    port: 9000
#
#service:
#  externalTrafficPolicy: Cluster

logs:
  loglevel: INFO
#
yaml:
  resources:
    requests:
      cpu: "100m"
      memory: "50Mi"
    limits:
      cpu: "300m"
      memory: "150Mi"
#  nodeSelector: {}
#  tolerations: []
#
api:
  insecure: true
  dashboard:
    enabled: true
#    certResolver: default
#    host: host.dashboard.com
#
# file_provider_config_map: traefik-config
#
acme:
  enabled: false
#  challengeType: "dns-01"
#  dnsProvider:
#    existingSecretName:
#    name: route53
#    route53:
#      AWS_ACCESS_KEY_ID: AWS_ACCESS_KEY_ID
#      AWS_SECRET_ACCESS_KEY: AWS_SECRET_ACCESS_KEY
#      AWS_REGION: AWS_REGION
